name: GitHub Pages Hugo Deploy

on:
  push:
    branches:
      - master # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
